import pygame

class Textureclass:

    def __init__(self, theme):
        path = "images/" + theme + "/"

        self.closed = pygame.image.load(path + "blank.gif")
        self.closed.convert()
        self.open0 = pygame.image.load(path + "open0.gif")
        self.open0.convert()
        self.open1 = pygame.image.load(path + "open1.gif")
        self.open1.convert()
        self.open2 = pygame.image.load(path + "open2.gif")
        self.open2.convert()
        self.open3 = pygame.image.load(path + "open3.gif")
        self.open3.convert()
        self.open4 = pygame.image.load(path + "open4.gif")
        self.open4.convert()
        self.open5 = pygame.image.load(path + "open5.gif")
        self.open5.convert()
        self.open6 = pygame.image.load(path + "open6.gif")
        self.open6.convert()
        self.open7 = pygame.image.load(path + "open7.gif")
        self.open7.convert()
        self.open8 = pygame.image.load(path + "open8.gif")
        self.open8.convert()
        self.bomb = pygame.image.load(path + "bombrevealed.gif")
        self.bomb.convert()
        self.bombdeath = pygame.image.load(path + "bombdeath.gif")
        self.bombdeath.convert()
        self.flaga = pygame.image.load(path + "bombflagged.gif")
        self.flaga.convert()

        self.won = pygame.image.load(path + "facewin.gif")
        self.won.convert()
        self.lost = pygame.image.load(path + "facedead.gif")
        self.lost.convert()
        self.smile = pygame.image.load(path + "crying_laughing.gif")
        self.smile.convert()

        self.top_left = pygame.image.load(path + "top_left.gif")
        self.top_left.convert()
        self.top_middle = pygame.image.load(path + "top_middle.gif")
        self.top_middle.convert()
        self.top_right = pygame.image.load(path + "top_right.gif")
        self.top_right.convert()
        self.side_left = pygame.image.load(path + "side_left.gif")
        self.side_left.convert()
        self.side_right = pygame.image.load(path + "side_right.gif")
        self.side_right.convert()
        self.bottom_left = pygame.image.load(path + "bottom_left.gif")
        self.bottom_left.convert()
        self.bottom_middle = pygame.image.load(path + "bottom_middle.gif")
        self.bottom_middle.convert()
        self.bottom_right = pygame.image.load(path + "bottom_right.gif")
        self.bottom_right.convert()
        self.smile = pygame.image.load(path + "crying_laughing.gif")
        self.smile.convert()

        self.time0 = pygame.image.load(path + "time0.gif")
        self.time0.convert()
        self.time1 = pygame.image.load(path + "time1.gif")
        self.time1.convert()
        self.time2 = pygame.image.load(path + "time2.gif")
        self.time2.convert()
        self.time3 = pygame.image.load(path + "time3.gif")
        self.time3.convert()
        self.time4 = pygame.image.load(path + "time4.gif")
        self.time4.convert()
        self.time5 = pygame.image.load(path + "time5.gif")
        self.time5.convert()
        self.time6 = pygame.image.load(path + "time6.gif")
        self.time6.convert()
        self.time7 = pygame.image.load(path + "time7.gif")
        self.time7.convert()
        self.time8 = pygame.image.load(path + "time8.gif")
        self.time8.convert()
        self.time9 = pygame.image.load(path + "time9.gif")
        self.time9.convert()